# Shared model params
n_cross_attn_heads: ${n_cross_attn_heads}
n_self_attn_heads: ${n_self_attn_heads}
dropout: ${dropout}


# Action autoencoder 
action_model:
  d_latent: ${d_latent}
  d_model: 768
  max_action_len: ${max_action_len}
  n_action_latents: 64
  n_encoder_self_attn_layers: 8
  n_decoder_self_attn_layers: 8
  n_cross_attn_heads: ${n_cross_attn_heads}
  n_self_attn_heads: ${n_self_attn_heads}
  dropout: ${dropout}
  model_name: ${pretrained_lm}

# Dynamics SSM.
dynamics_model: 
  n_precept_latents: 64
  d_model: 768
  n_self_attn_layers: 8
  n_cross_attn_heads: ${n_cross_attn_heads}
  n_self_attn_heads: ${n_self_attn_heads}
  dropout: ${dropout}
  model_name: ${pretrained_lm}